### ISSUE TITLE
Concurrency feature

### ISSUE THREAD

**Issue by rahqis** [irods/irods_testing_environment_UI#4]
Needs to enable --concurrent-test-executor-count flag to speed up running multiple tests

**Comment by rahqis** [comment]
Enabled using number input, but note: be no max concurrency count is listed or configured on device, so user must be aware of how much their machine can/should handle.

**Comment by trel** [comment]
part of the initial commit 221e9771f0ff3405428d9dfbe984cfff9d4b37ea in this repository
