### ISSUE TITLE
View XML Files

### ISSUE THREAD

**Issue by rahqis** [irods/irods_testing_environment_UI#6]
As of now, viewing XMLs was not possible. No information related to the log file directory was stored.

**Comment by rahqis** [comment]
Resolved by creating a set of get requests dealing with retrieving and collecting XMLs. XMLs can be viewed on UI by clicking their respective XML button after test results appear

**Comment by trel** [comment]
part of the initial commit 221e9771f0ff3405428d9dfbe984cfff9d4b37ea in this repository
